apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  {{- range .Values.api.ingress }}
  - host: {{ . }}
    http:
      paths:
        - path: /swagger
          pathType: Prefix
          backend:
            service:
              name: {{ $.Release.Name }}-api-service
              port:
                number: 80
  {{- end }}
