apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-configmap
data:
  Mongo_Host: {{ template "mongodb.serviceName" . }}
  Mongo_Database: {{ .Values.mongodb.databaseName  }}