apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-configmap
data:
  Mongo_User: {{ .Values.mongodb.auth.username | b64enc | quote }}
  Mongo_Password: {{ .Values.mongodb.auth.password | b64enc | quote }}